[build]
  command = "npm run netlify-build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.x"  # For React 19 compatibility
  NEXT_TELEMETRY_DISABLED = "1"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
