[build]
  command = "next build"
  publish = ".next/static"

[build.environment]
  NODE_VERSION = "20.x"  # For React 19 compatibility
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects are crucial for Next.js 15 with App Router
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/.netlify/functions/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
